package edu.desu.sortsearchutils;

import edu.desu.helperstaticmethods.HelperStaticMethods;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class SelectionSortTests {

    @Test
    @DisplayName("Test selectionSort on standard unsorted array")
    void testSelectionSortUnsortedArray() {
        int[] input = {5, 3, 1, 4, 2};
        int[] expected = {1, 2, 3, 4, 5};
        SelectionSort.selectionSort(input);
        Assertions.assertArrayEquals(expected, input);
    }

    @Test
    @DisplayName("Test selectionSort on already sorted array")
    void testSelectionSortAlreadySortedArray() {
        int[] input = {1, 2, 3, 4, 5};
        int[] expected = {1, 2, 3, 4, 5};
        SelectionSort.selectionSort(input);
        Assertions.assertArrayEquals(expected, input);
    }

    @Test
    @DisplayName("Test selectionSort on reverse sorted array")
    void testSelectionSortReverseSortedArray() {
        int[] input = {5, 4, 3, 2, 1};
        int[] expected = {1, 2, 3, 4, 5};
        SelectionSort.selectionSort(input);
        Assertions.assertArrayEquals(expected, input);
    }

    @Test
    @DisplayName("Test selectionSort on array with duplicate elements")
    void testSelectionSortArrayWithDuplicates() {
        int[] input = {3, 1, 2, 3, 1};
        int[] expected = {1, 1, 2, 3, 3};
        SelectionSort.selectionSort(input);
        Assertions.assertArrayEquals(expected, input);
    }

    @Test
    @DisplayName("Test selectionSort on array with negative numbers")
    void testSelectionSortArrayWithNegativeNumbers() {
        int[] input = {-3, 5, -1, 0, 2};
        int[] expected = {-3, -1, 0, 2, 5};
        SelectionSort.selectionSort(input);
        Assertions.assertArrayEquals(expected, input);
    }

    @Test
    @DisplayName("Test selectionSort on empty array")
    void testSelectionSortEmptyArray() {
        int[] input = {};
        int[] expected = {};
        SelectionSort.selectionSort(input);
        Assertions.assertArrayEquals(expected, input);
    }

    @Test
    @DisplayName("Test selectionSort on single element array")
    void testSelectionSortSingleElementArray() {
        int[] input = {42};
        int[] expected = {42};
        SelectionSort.selectionSort(input);
        Assertions.assertArrayEquals(expected, input);
    }

    @Test
    @DisplayName("Test selectionSort throws NullPointerException on null input")
    void testSelectionSortNullArray() {
        Assertions.assertThrows(NullPointerException.class, () -> SelectionSort.selectionSort(null));
    }

    @Test
    @DisplayName("Test selectionSort on scrambled array generated by helper method")
    void testSelectionSortScrambledArray() {
        int size = 100;
        int[] data = HelperStaticMethods.generateScrambledIntArray(size);
        int[] expected = HelperStaticMethods.generateSequentialIntArray(size);
        SelectionSort.selectionSort(data);
        Assertions.assertArrayEquals(expected, data);
    }
}
